"""Trying to make stuffs work

Revision ID: a7b92406654b
Revises: 9cf282cbbe9f
Create Date: 2026-01-13 14:35:43.531279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b92406654b'
down_revision: Union[str, Sequence[str], None] = '9cf282cbbe9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_author_preference_author_name'), table_name='user_author_preference')
    op.drop_index(op.f('ix_user_author_preference_user_id'), table_name='user_author_preference')
    op.drop_table('user_author_preference')
    op.drop_index(op.f('ix_user_taste_profiles_user_id'), table_name='user_taste_profiles')
    op.drop_table('user_taste_profiles')
    op.drop_index(op.f('ix_user_genre_preferences_genre'), table_name='user_genre_preferences')
    op.drop_index(op.f('ix_user_genre_preferences_user_id'), table_name='user_genre_preferences')
    op.drop_table('user_genre_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_genre_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('genre', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_genre_preferences_user_id'), 'user_genre_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_genre_preferences_genre'), 'user_genre_preferences', ['genre'], unique=False)
    op.create_table('user_taste_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('preferred_place', sa.VARCHAR(), nullable=True),
    sa.Column('preferred_length', sa.VARCHAR(), nullable=True),
    sa.Column('likes_series', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_taste_profiles_user_id'), 'user_taste_profiles', ['user_id'], unique=False)
    op.create_table('user_author_preference',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('author_name', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_author_preference_user_id'), 'user_author_preference', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_author_preference_author_name'), 'user_author_preference', ['author_name'], unique=False)
    # ### end Alembic commands ###
